//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRPZ_2.FileService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileService.IDataService")]
    public interface IDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetFileFSId", ReplyAction="http://tempuri.org/IDataService/GetFileFSIdResponse")]
        int GetFileFSId(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetFileFSId", ReplyAction="http://tempuri.org/IDataService/GetFileFSIdResponse")]
        System.Threading.Tasks.Task<int> GetFileFSIdAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetFilePart", ReplyAction="http://tempuri.org/IDataService/GetFilePartResponse")]
        byte[] GetFilePart(int FSId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetFilePart", ReplyAction="http://tempuri.org/IDataService/GetFilePartResponse")]
        System.Threading.Tasks.Task<byte[]> GetFilePartAsync(int FSId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceChannel : TRPZ_2.FileService.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<TRPZ_2.FileService.IDataService>, TRPZ_2.FileService.IDataService {
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetFileFSId(string path) {
            return base.Channel.GetFileFSId(path);
        }
        
        public System.Threading.Tasks.Task<int> GetFileFSIdAsync(string path) {
            return base.Channel.GetFileFSIdAsync(path);
        }
        
        public byte[] GetFilePart(int FSId) {
            return base.Channel.GetFilePart(FSId);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetFilePartAsync(int FSId) {
            return base.Channel.GetFilePartAsync(FSId);
        }
    }
}
